### ISSUE TITLE
conversion bug in convertJson4ESindexing.py 

### ISSUE THREAD

**Issue by newgene** [WebsmartAPI/smartAPI#3]
When saving this API metadata, 500 server error is returned. 

API metadata: https://raw.githubusercontent.com/mjstealey/datatranslator/develop/swagger-editor/swagger.yaml  (need to uncomment the line of "responsibleDeveloper")

The exception happens in convertJson4ESindexing.py:

```
    Traceback (most recent call last):
      File "/home/ubuntu/smartapi/devpy3/lib/python3.4/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/ubuntu/smartapi/smartAPI/src/api/index.py", line 115, in post
        res = esq.save_api(data, overwrite=overwrite)
      File "/home/ubuntu/smartapi/smartAPI/src/api/es.py", line 116, in save_api
        _doc = convert_file(api_doc)
      File "/home/ubuntu/smartapi/smartAPI/src/esConverter/convertJson4ESindexing.py", line 86, in convert_file
        path_obj[stuff] = the_file_contents[key][pathname_key][method_key].get(stuff)
    AttributeError: 'list' object has no attribute 'get'
```

**Comment by newgene** [comment]
Fixed in 383c2e9.
